name: Publish Docker image in dockerhub

on:
  release:
    types: [published]
  push:
    branches:
      - "master"
       
jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
      packages: write 
    steps:
    
    
      - name: add tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0                
        with:
          github_token: ${{ secrets.gh_token }}
          default_bump: major
          
          
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
           git describe --tags --always
           


          

                    

      
