name: Publish Docker image in dockerhub

on:
  release:
    types: [published]
  push:
    branches:
      - "master"
       
jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      repository-projects: write
      packages: write 
    steps:    
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
             git config user.name github-actions
             git config user.email github-actions@github.com
             git reset --hard HEAD~1
             git commit -m "Reverting to the state of the project"
             git merge origin/master            
             git push
          

                    

      
