name: Publish Docker image in dockerhub

on:
  release:
    types: [published]
  push:
    branches:
      - "master"
       
jobs:
  push_to_registries:
    name: Push Docker image
    runs-on: ubuntu-latest
    env:
      db: db.txt
    permissions:
      contents: write
      repository-projects: write
      packages: write 
    steps:  
     - name: Connect to host with proxy with out password     
       run: |
           mkdir ~/.ssh
           eval `ssh-agent -s`
           ssh-add - <<< "${{secrets.KEY}}" 
           ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           ssh ${{ secrets.USERNAME_HOST }}@${{ secrets.HOST_IP }} -o ProxyCommand="ssh -W %h:%p ${{ secrets.USERNAME_PROXY }}@${{ secrets.PROXY_HOST }}" -o StrictHostKeyChecking=no "ls |  sort -V | tail -n 1 >> ${{ env.db }} && cat ${{ env.db }} && mysql -u root wordpress < cat ${{ env.db }}"
