name: Check pods in SA
on: 
  push:
  #schedule:
    #- cron: "* */12 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Connect to host with proxy with out password
        id: get_pods
        run: |
           mkdir ~/.ssh
           eval `ssh-agent -s`
           ssh-add - <<< "${{secrets.KEY}}" 
           ssh-keyscan -H ${{ secrets.PROXY_HOST }} >> ~/.ssh/known_hosts
           echo 'CONTENT_ENV<<EOF' >> $GITHUB_ENV
           ssh ${{ secrets.USERNAME_HOST }}@${{ secrets.HOST_IP }} -o ProxyCommand="ssh -W %h:%p ${{ secrets.USERNAME_PROXY }}@${{ secrets.PROXY_HOST }}" >> $GITHUB_ENV  
           echo 'EOF' >> $GITHUB_ENV
          
 
      - name: Slack Notification
        if: steps.out_pods_failed.outputs.crashed > 1
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: crashed_pods-from-sa
          SLACK_COLOR: '#FF0000'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'We have crashed pods!!!'
          SLACK_TITLE: 'ALERT! Check pods_crashed.log in artifact'
          SLACK_USERNAME: Kostenko Pavel
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

        

